language: node_js
sudo: required
dist: trusty

services:
  - rabbitmq

node_js:
  - '4'
  - '6'
  - '8'

env:
    - TEST_SUITE=senecajs/seneca-transport
    - TEST_SUITE=senecajs/seneca-entity
    - TEST_SUITE=senecajs/seneca-mem-store
    - TEST_SUITE=senecajs/seneca-user
    - TEST_SUITE=senecajs/seneca-balance-client
    - TEST_SUITE=senecajs/seneca-repl
    - TEST_SUITE=senecajs/seneca-joi
    - TEST_SUITE=senecajs/seneca-jsonfile-store
    - TEST_SUITE=senecajs/seneca-level-store
    - TEST_SUITE=senecajs/seneca-pino-logger
    - TEST_SUITE=senecajs/seneca-web
    - TEST_SUITE=senecajs/seneca-basic
    - TEST_SUITE=senecajs/seneca-registry
    - TEST_SUITE=senecajs/seneca-amqp-transport

matrix:
  exclude:
    - node_js: '4'
      env: TEST_SUITE=senecajs/seneca-amqp-transport
      

before_script:
  - TIMEOUT_MULTIPLIER=8
  - echo "TEST_SUITE:$TEST_SUITE"
  - TEST_SUITE_FOLDER=$(basename $TEST_SUITE)
  - echo "TEST_SUITE_FOLDER:$TEST_SUITE_FOLDER"
  - SENECA_INSTALL=https://github.com/senecajs/seneca;
  - echo "SENECA_INSTALL:$SENECA_INSTALL";
  - git clone https://github.com/$TEST_SUITE;
  - cd $TEST_SUITE_FOLDER;
  - mkdir -p tmp
  - echo "module.exports = " > tmp/travis-build-npm-details.js
  - npm info $TEST_SUITE_FOLDER --no-progress >> tmp/travis-build-npm-details.js
  - MODULE_VERSION=`node -e "console.log(require('./tmp/travis-build-npm-details.js')['dist-tags'].latest)"`
  - rm -f tmp/travis-build-npm-details.js
  - git checkout v$MODULE_VERSION || git checkout $MODULE_VERSION
  - npm i;
  - npm uninstall seneca;
  - npm install $SENECA_INSTALL;


cache:
  directories:
    - node_modules

